spring.application.name=reservasi

server.port = 8100

#definisikan akses ke DB disini
spring.datasource.url= jdbc:postgresql://localhost:5432/db_medicall
spring.datasource.username= postgres
spring.datasource.password= postgres

#setting DB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

smtp.host = smtp.gmail.com
smtp.port = 587